spring:
  application:
    name: library-api

  datasource:
    url: jdbc:mysql://db:3306/library_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true